# Generated by Django 3.2.2 on 2021-05-11 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseList',
            fields=[
                ('courseID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('courseName', models.CharField(default=None, max_length=100, null=True)),
                ('studentNumber', models.IntegerField(default=0)),
                ('level', models.CharField(max_length=10)),
                ('tuitionFeesByVND', models.IntegerField()),
                ('schedule', models.CharField(max_length=50)),
                ('courseLengthByMonth', models.IntegerField(default=0)),
                ('beginDate', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('studyRoom', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('resultID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('absentDays', models.IntegerField(default=0)),
                ('GPA', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentID', models.CharField(max_length=20)),
                ('studentName', models.CharField(max_length=50)),
                ('studentEmail', models.CharField(max_length=100, null=True)),
                ('DOB', models.DateField(default=None, null=True)),
                ('studentGender', models.CharField(default=None, max_length=6, null=True)),
                ('phoneNumber', models.CharField(default=None, max_length=10, null=True)),
                ('note', models.TextField(blank=True, default=None, null=True)),
                ('belongToCourse', models.ManyToManyField(to='home.CourseList')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('teacherID', models.CharField(default=None, max_length=10, primary_key=True, serialize=False)),
                ('teacherName', models.CharField(max_length=200, null=True)),
                ('teacherDOB', models.DateField(default=None, null=True)),
                ('teacherGender', models.CharField(max_length=6, null=True)),
                ('phoneNumber', models.CharField(max_length=200, null=True)),
                ('teacherEmail', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='WebUser',
        ),
        migrations.AddField(
            model_name='studentresult',
            name='belongToStudent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.students'),
        ),
        migrations.AddField(
            model_name='courselist',
            name='manageTeacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.teachers'),
        ),
    ]
