# Generated by Django 3.2.1 on 2021-05-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courselist',
            old_name='courseLength',
            new_name='courseLengthByMonth',
        ),
        migrations.RenameField(
            model_name='courselist',
            old_name='tuitionFees',
            new_name='tuitionFeesByVND',
        ),
        migrations.RemoveField(
            model_name='courselist',
            name='studentList',
        ),
        migrations.AddField(
            model_name='students',
            name='belongToCourse',
            field=models.ManyToManyField(to='home.CourseList'),
        ),
    ]
