# Generated by Django 3.2.1 on 2021-05-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210510_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselist',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
