# Generated by Django 3.2.1 on 2021-05-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_courselist_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselist',
            name='studyRoom',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
