# Generated by Django 3.2.1 on 2021-05-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_courselist_studyroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='parentsPhoneNumber',
        ),
        migrations.AddField(
            model_name='students',
            name='phoneNumber',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='courselist',
            name='note',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
